server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
    }

    location /metrics {
        stub_status on;
        allow 192.168.16.1;  # Chỉ cho phép truy cập từ localhost
        deny all;         # Cấm tất cả các IP khác
    }
}
